# Generated by Django 6.0.2 on 2026-02-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_has_agreed_terms_user_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlankListedTokens',
            new_name='BlackListedTokens',
        ),
    ]
