# Generated by Django 6.0.2 on 2026-02-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_blanklistedtokens_blacklistedtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtokens',
            name='jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
