# Generated by Django 6.0.2 on 2026-02-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_logintracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintracker',
            old_name='last_seen',
            new_name='platform',
        ),
    ]
