# Generated by Django 6.0.2 on 2026-05-31 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('view_properties', 'Can view properties'), ('add_properties', 'Can add properties'), ('edit_properties', 'Can edit properties'), ('delete_properties', 'Can delete properties'), ('view_users', 'Can view users'), ('add_users', 'Can add users'), ('edit_users', 'Can edit users'), ('delete_users', 'Can delete users'), ('view_roles', 'Can view roles'), ('add_roles', 'Can add roles'), ('edit_roles', 'Can edit roles'), ('delete_roles', 'Can delete roles'), ('view_reports', 'Can view reports'), ('generate_reports', 'Can generate reports'), ('manage_settings', 'Can manage system settings'), ('view_financial_data', 'Can view financial data'), ('edit_financial_data', 'Can edit financial data'), ('view_sales_data', 'Can view sales data'), ('edit_sales_data', 'Can edit sales data'), ('view_marketing_data', 'Can view marketing data'), ('edit_marketing_data', 'Can edit marketing data'), ('manage_permissions', 'Can manage user permissions'), ('manage_roles', 'Can manage user roles'), ('view_audit_logs', 'Can view audit logs'), ('manage_audit_logs', 'Can manage audit logs'), ('view_system_health', 'Can view system health'), ('manage_system_health', 'Can manage system health'), ('view_user_activity', 'Can view user activity'), ('manage_user_activity', 'Can manage user activity'), ('view_notifications', 'Can view notifications'), ('manage_notifications', 'Can manage notifications'), ('view_support_tickets', 'Can view support tickets'), ('manage_support_tickets', 'Can manage support tickets'), ('view_api_usage', 'Can view API usage'), ('manage_api_usage', 'Can manage API usage')], max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('buyer', 'Buyer'), ('super_admin', 'Super Admin'), ('manager', 'Manager'), ('finance_admin', 'Finance Admin'), ('sales_admin', 'Sales Admin'), ('marketing_admin', 'Marketing Admin')], max_length=150, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('buyer', 'Buyer'), ('super_admin', 'Super Admin'), ('manager', 'Manager'), ('finance_admin', 'Finance Admin'), ('sales_admin', 'Sales Admin'), ('marketing_admin', 'Marketing Admin')], default='buyer', max_length=50),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='api.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='api.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='api.roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
