# Generated by Django 6.0.2 on 2026-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_permission_roles_alter_user_role_rolepermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
