# Generated by Django 6.0.2 on 2026-05-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_roles_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permissions',
            field=models.ManyToManyField(related_name='permission_roles', to='api.permission', verbose_name='Permissions'),
        ),
    ]
