# Generated by Django 6.0.2 on 2026-05-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_rolepermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='permission_roles', to='api.permission', verbose_name='Permissions'),
        ),
    ]
