# Generated by Django 6.0.2 on 2026-06-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_rolepermission_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='permission_roles', to='api.permission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='api.roles'),
        ),
    ]
