# Generated by Django 6.0.2 on 2026-06-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_rolepermission_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions', to='api.rolepermission'),
        ),
    ]
