# Generated by Django 6.0.2 on 2026-06-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userrole_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions', to='api.permission', verbose_name='Extra Permissions'),
        ),
    ]
