# Generated by Django 6.0.2 on 2026-06-04 04:14

import django.contrib.auth.models
import django.db.models.deletion
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userrole_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now=True)),
                ('created_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realtors',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_realtor', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Realtors',
                'verbose_name_plural': 'Realtors',
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('custombasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.custombasemodel')),
                ('upfront_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='api.realtors')),
            ],
            bases=('api.custombasemodel',),
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('custombasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.custombasemodel')),
                ('referral_date', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.realtors')),
                ('sponsor', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.referrals')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.custombasemodel', models.Model),
        ),
    ]
