# Generated by Django 6.0.2 on 2026-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_custombasemodel_realtors_commission_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtors',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='realtors',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtors',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('UBA', 'UBA'), ('FCMB', 'FCMB'), ('WEMA', 'Wema Bank'), ('OPAY', 'OPay'), ('MONIEPOINT', 'Moniepoint')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realtors',
            name='bank_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realtors',
            name='bank_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=200),
        ),
    ]
