# Generated by Django 6.0.2 on 2026-06-08 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_estateclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[], max_length=150)),
                ('property_types', models.CharField(choices=[], max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('features', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
