# Generated by Django 6.0.2 on 2026-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='properties',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
