# Generated by Django 6.0.2 on 2026-06-11 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_properties_actual_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPlots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='properties',
            name='has_plots',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DateTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_plan', models.CharField(choices=[], max_length=150)),
                ('status', models.CharField(choices=[], max_length=150)),
                ('plots', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('sales_date', models.DateField(auto_now_add=True)),
                ('sales_date_time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_client', to='api.estateclients')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_property', to='api.properties')),
                ('realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_realtor', to='api.realtors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
