# Generated by Django 6.0.2 on 2026-06-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_propertyplots_properties_has_plots_datetracker_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_date_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
