# Generated by Django 6.0.2 on 2026-06-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_sales_sales_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='property',
            new_name='properties',
        ),
    ]
