# Generated by Django 6.0.2 on 2026-06-13 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_property_sales_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyExtras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extras', models.JSONField(default={})),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.properties')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PropertyPlots',
        ),
    ]
