# Generated by Django 6.0.2 on 2026-06-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_propertyextras_delete_propertyplots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyextras',
            name='extras',
            field=models.TextField(default=True),
        ),
    ]
