# Generated by Django 6.0.2 on 2026-06-13 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_propertyextras_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPlots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_number', models.CharField(max_length=150)),
                ('plot_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('uid', models.CharField(max_length=250)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.properties')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PropertyExtras',
        ),
    ]
