# Generated by Django 6.0.2 on 2026-06-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_propertyplots_delete_propertyextras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
