# Generated by Django 6.0.2 on 2026-06-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_properties_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyplots',
            name='plot_number',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyplots',
            name='uid',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
