# Generated by Django 6.0.2 on 2026-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_propertyplots_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyplots',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
