# Generated by Django 6.0.2 on 2026-06-15 10:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_propertyplots_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plots', models.ManyToManyField(to='api.propertyplots')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_plots', to='api.sales')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
