# Generated by Django 6.0.2 on 2026-06-19 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_salesplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='on_promo',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=150),
        ),
        migrations.CreateModel(
            name='SalesPaymentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_name', models.CharField(max_length=250)),
                ('billing_period_number', models.IntegerField(default=0)),
                ('billing_date', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=150)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_payment_plan', to='api.sales')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
