# Generated by Django 6.0.2 on 2026-06-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_sales_on_promo_salespaymentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespaymentplan',
            name='billing_amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
