# Generated by Django 6.0.2 on 2026-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_salespaymentplan_billing_amount_to_pay'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salespaymentplan',
            constraint=models.UniqueConstraint(fields=('sales',), name='unique_sales'),
        ),
    ]
