# Generated by Django 6.0.2 on 2026-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_salespaymentplan_unique_sales'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salespaymentplan',
            name='unique_sales',
        ),
        migrations.AddConstraint(
            model_name='salespaymentplan',
            constraint=models.UniqueConstraint(fields=('sales', 'billing_date'), name='unique_sales_billing_date'),
        ),
    ]
