# Generated by Django 6.0.2 on 2026-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_salespaymentplan_unique_sales_billing_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salespaymentplan',
            name='unique_sales_billing_date',
        ),
        migrations.AddConstraint(
            model_name='salespaymentplan',
            constraint=models.UniqueConstraint(fields=('sales',), name='unique_sales'),
        ),
    ]
