# Generated by Django 6.0.2 on 2026-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_salespaymentplan_unique_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespaymentplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=150),
        ),
    ]
